### PR TITLE
Fix control panel URL

### PR DESCRIPTION
**Pull request by frangio**

### CODE REVIEW

**Comment by hilary** [comment]
Nice! Thanks for catching that. :)

**Comment by andrewsomething** [comment]
Looks like there are a few more occurrences of this typo in the same file. Might would be nice to fix them all in one go. (And maybe a new commit would get Travis to re-run? Not sure why it's been hanging this long...)

https://github.com/digitalocean/doctl/blob/d1ba71b5ad4f96eff0a3214a97e169e2e77889a7/commands/auth.go#L75

https://github.com/digitalocean/doctl/blob/d1ba71b5ad4f96eff0a3214a97e169e2e77889a7/commands/auth.go#L85

**Comment by frangio** [comment]
Sure! Fixed them.

**Comment by MattIPv4** [comment]
Hey, @frangio - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

**Pull request merged**
