### PR TITLE
Add multi-stage build, non-root user, multi-arch builds in Dockerfile

### PR DESCRIPTION
**Pull request by BobyMCbobs**
# Goals

Adjust container build to

- allow the CLI to be built with-in the container build stage
- run as non-root, so it's less privileged
- allow building for different architectures

### CODE REVIEW

**Comment by andrewsomething** [comment]
Hi @BobyMCbobs. Thanks for the PR!

That specific `Dockerfile` was written back before we published official images to [Docker Hub](https://hub.docker.com/r/digitalocean/doctl). It was intended to allow people to build images with the official released binary. That's why it downloads the binary from GitHub. Now that we provide the official images, I do think it would be good to simplify things in this repo and improve the default `Dockerfile`. We should probably collapse collapse `Dockerfile`, `Dockerfile.build`, and `Dockerfile.cntr` into one file.

The one issue with this PR is that it builds things differently than we do elsewhere. I'd love to keep the builds more consistent so there is less to debug. E.g. It doesn't set [the ldflags needed](https://github.com/digitalocean/doctl/blob/master/scripts/_build.sh) for version on commit info in `doctl version` output.

Though in order to use `make native` and allow for building with other arches, the `GOARCH` variable in the makefile needs to be overridable: 

https://github.com/digitalocean/doctl/blob/master/Makefile#L35-L38

Let us know if you're interested in making those changes. If not, I can probably prioritize getting doing so.

**Comment by BobyMCbobs** [comment]
I would recommend having a Dockerfile like this around, as it makes the builds highly portable.

I'd prefer not to make the changes in the Makefile, but it would be great to have more multi-arch builds (such as _arm64_).

One thing that it's important to address is, running as non-root. The container should not need to run as root. In the changes, it runs as the user _user_ / _1000_.

**Comment by andrewsomething** [comment]
Totally understandable! Though I think this approach will be more maintainable for us in the long run. I'd appreciate your feedback on https://github.com/digitalocean/doctl/pull/860. It includes the non-root user and should allow building multi-arch with the same interface as this PR: 

    docker build --build-arg GOARCH=arm64 . -t doctl

**Comment by BobyMCbobs** [comment]
> Totally understandable! Though I think this approach will be more maintainable for us in the long run. I'd appreciate your feedback on #860. It includes the non-root user and should allow building multi-arch with the same interface as this PR:
> 
> ```
> docker build --build-arg GOARCH=arm64 . -t doctl
> ```

@andrewsomething, this looks pretty good.

Perhaps one last thing would be to make sure that the Go binary is statically compiled as I couldn't see any args in the [build script](https://github.com/digitalocean/doctl/blob/master/scripts/_build.sh#L29) for this. e.g: https://github.com/digitalocean/doctl/pull/855/files#diff-3254677a7917c6c01f55212f86c57fbfR9-R12

**Pull request closed without merging**
