### PR TITLE
ssh: windows support for command forwarding

### PR DESCRIPTION
**Pull request by xmudrii**
Looks like I managed to make this work.
I don't have Windows box on my own, but I tested on one I found and it seems to work very well. If you have Windows box, it could be useful to test further.

Also, tests for internal SSH looks like they are only checking correctness of private key, but if there is something to add, I'll do it. =)

cc @nanzhong @grampajoe

### CODE REVIEW

**Comment by nanzhong** [comment]
I unfortunately don't have a windows box handy handy to test this. I'll try and setup an env sometime this weekend to test this.

**Comment by mauricio** [comment]
@xmudrii mind rebasing and running the build again here?

**Comment by xmudrii** [comment]
Will be rebased in a moment :)

**Comment by xmudrii** [comment]
@mauricio Rebased. Tests are currently in progress :green_apple:

**Pull request merged**
