### PR TITLE
Add support for opensearch

### PR DESCRIPTION
**Pull request by bhardwajRahul**
This PR aims at adding support for Opensearch in DOCTL.

### CODE REVIEW

**Review by andrewsomething — APPROVED** [review]
:+1:  LGTM!

**Comment by pwalsh** [comment]
This PR seems to imply that there will be Open Search as a managed database offering, but, I can't find any other info about that. @andrewsomething @bhardwajRahul is there any way I can get early access to open search managed databases?

**Comment by bhardwajRahul** [comment]
> This PR seems to imply that there will be Open Search as a managed database offering, but, I can't find any other info about that. @andrewsomething @bhardwajRahul is there any way I can get early access to open search managed databases?

 we have enabled this for our beta customers only.

**Comment by pwalsh** [comment]
@bhardwajRahul thank you, that would be amazing. My email is available at https://github.com/pwalsh

**Comment by pwalsh** [comment]
@bhardwajRahul 😃

**Comment by bhardwajRahul** [comment]
@pwalsh I have enabled you over opensearch beta. Someone from DO will approach you soon.

**Pull request merged**
