### PR TITLE
Add certificate commands.

### PR DESCRIPTION
**Pull request by viola**
This changeset implements certificate cmds and patches following error as a results of getting the latests from https://github.com/digitalocean/godo:
```
# github.com/digitalocean/doctl/do
../do/volumes.go:36: cannot use opt (type *godo.ListOptions) as type *godo.ListVolumeParams in argument to a.client.Storage.ListVolumes
FAIL	github.com/digitalocean/doctl/commands [build failed]
```

## Certificate commands
`$ doctl compute certificate`

```
certificate is used to access certificate commands

Usage:
  doctl compute certificate [command]

Available Commands:
  get         get certificate
  create      create new certificate
  list        list certificates
  delete      delete certificate

Flags:
  -h, --help   help for certificate

Global Flags:
  -t, --access-token string   API V2 Access Token
  -c, --config string         config file (default is $HOME/.config/doctl/config.yaml)
  -o, --output string         output format [text|json] (default "text")
      --trace                 trace api access
  -v, --verbose               verbose output

Use "doctl compute certificate [command] --help" for more information about a command.
```

## Get certificate `certificate get <id>`
```
get certificate

Usage:
  doctl compute certificate get <id> [flags]

Aliases:
  get, g
```

`$ doctl compute certificate get 162ded9f-97a3-4509-b26f-afa8b46c1b19`
```
ID					Name		SHA-1 Fingerprint				Expiration Date		Created At
162ded9f-97a3-4509-b26f-afa8b46c1b19	new-cert-01	6a70e706ec245cfb66956b150c56befcf12a5d5a	2022-01-26T15:50:00Z	2017-02-21T01:48:43Z
```

## Create new certificate `certificate create`
```
create new certificate

Usage:
  doctl compute certificate create [flags]

Aliases:
  create, c


Flags:
      --certificate-chain-path string   path to a certificate chain (required)
      --leaf-certificate-path string    path to a certificate leaf (required)
      --name string                     certificate name (required)
      --private-key-path string         path to a private key for the certificate (required)
```

`$ doctl compute certificate create --name web-cert-01 --private-key-path ~/my-secrets/priv-key.pem --certificate-chain-path ~/my-secrets/cer-chain.crt  --leaf-certificate-path ~/my-secrets/leaf-cer.crt`

```
ID					Name		SHA-1 Fingerprint				Expiration Date		Created At
96c134b2-33b4-44d2-a8b6-cdfa5e749c49	web-cert-01	6a70e706ec245cfb66956b150c56befcf12a5d5a	2022-01-26T15:50:00Z	2017-02-21T16:56:33Z
```

## Get all certificates `certificate list`
`$ doctl compute certificate list`

```
ID					Name		SHA-1 Fingerprint				Expiration Date		Created At
162ded9f-97a3-4509-b26f-afa8b46c1b19	new-cert-01	6a70e706ec245cfb66956b150c56befcf12a5d5a	2022-01-26T15:50:00Z	2017-02-21T01:48:43Z
96c134b2-33b4-44d2-a8b6-cdfa5e749c49	web-cert-01	6a70e706ec245cfb66956b150c56befcf12a5d5a	2022-01-26T15:50:00Z	2017-02-21T16:56:34Z
```

## Delete certificate `certificate delete <id>`
```
delete certificate

Usage:
  doctl compute certificate delete <id> [flags]

Aliases:
  delete, d, rm


Flags:
  -f, --force   Force certificate delete
```

`$ doctl compute certificate rm ff94ed72-2566-4392-ba8b-5023bd22065a`

```
Warning: Are you sure you want to delete this certificate (y/N) ? y
```

### CODE REVIEW

**Comment by xmudrii** [comment]
I'm on mobile but this looks good. :1:The only addition that could be useful is list filtering, like for with Droplets, Snap‎shots or Volumes. Not needed now, we can add it later, once this gets merged.Other than that, LGTM                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.

**Comment by rafaelrosafu** [comment]
It looks good. We might need to change `--certificate-chain-path` to be optional, with self-signed certs it shouldn't be required, but this needs to be changed on the API first. Just make sure it's easy to change in the future.

**Comment by viola** [comment]
@xmudrii thank you for your review. Noted: "The only addition that could be useful is list filtering, like for with Droplets, Snap‎shots or Volumes"

**Comment by viola** [comment]
@rafaelrosafu thank you for your review, it should be straightforward to make `--certificate-chain-path` flag optional by removing `requiredOpt()` from https://github.com/digitalocean/doctl/pull/191/files#diff-e864d706abdc7acacea0a51bc33135e9R43

**Comment by xmudrii** [comment]
@viola it will not do the job, in case you remove `requiredOpt()`, you will get error from API, as Chain Path is required by API.
At least it is stated as required in [docs](https://developers.digitalocean.com/documentation/v2/#create-a-new-certificates).

**Comment by xmudrii** [comment]
@viola how does Load Balancers go on? is somebody working on it or some contributor can take on it =D

**Comment by viola** [comment]
@xmudrii sorry I meant that removing `requiredOpt()` will make `--certificate-chain-path` flag optional given that the api is adjusted accordingly beforehand.
RE: load-balancer cmd - I'm working on it as well, expect PR within a day or so :) - will ping you when PR is ready for review.

**Comment by xmudrii** [comment]
@viola oh, then I miss understood you. =)
sounds great, i'm awaiting it =D

**Comment by mauricio** [comment]
Looks great! 👍

**Comment by tam7t** [comment]
👍

**Pull request merged**
