### PR TITLE
Implementing new unified Snapshots API

### PR DESCRIPTION
**Pull request by xmudrii**
https://developers.digitalocean.com/documentation/changelog/api-v2/add-volume-snapshots/
https://github.com/digitalocean/godo/pull/108

I done this to for myself, I needed something, and I wanted to try out my Go skills. I didn't took me long, but I want to know a few things.

Did I stole someones job? :P
How is it looking?

I'll do tests soon, and add needed function.
Will cc some of mainters.

cc @mchitten @hugocorbucci @nanzhong @aybabtme

### CODE REVIEW

**Comment by aybabtme** [comment]
this is shaping up nicely, ping me (@-aybabtme) when you think it's ready!

**Comment by xmudrii** [comment]
Tests will fail now, I'm implementing units for it.

@aybabtme It's not ready, but I got into problem. How can I generate mocks for Snapshots?
I looked under do/mocks but all files there are autogen.

I committed what I tried, but tm.snapshots doesn't exist
```
# github.com/digitalocean/doctl/commands
./snapshots_test.go:30: tm.snapshots undefined (type *tcMocks has no field or method snapshots)
FAIL	github.com/digitalocean/doctl/commands [build failed]
```

**Comment by aybabtme** [comment]
@xmudrii mocks are generated with https://github.com/vektra/mockery

**Comment by xmudrii** [comment]
@aybabtme found out it now, installed but what command I need to use to generate it?
Will `mockery -all` do the job? I tried with `mockery -name` with some combinations of names (like Snapshot, Snapshots, Snapshot(s)Service) but that doesn't work

**Comment by xmudrii** [comment]
@aybabtme It's ready!

Note: I changed Go version in `.travis.yml` from 1.6 to 1.7. doctl 1.5 is built with Go 1.7 so I think it's OK to change it in `.travis.yml` too. I'll revert it if that makes any problem.

I tried as best as I can. =) I hope it's good enough for DO, if there is something I can fix, I'll be glad to do it =)

**Comment by aybabtme** [comment]
That's working pretty well and the code is A+, thanks a ton @xmudrii !

**Comment by xmudrii** [comment]
No problem and thanks, glad to know it helped. :+1: :D

**Pull request merged**
