### PR TITLE
Fixed doctl's configuration file location for OS X

### PR DESCRIPTION
**Pull request by StevenH1901**
After installing doctl with brew, the configuration file is not at `${XDG_CONFIG_HOME}/doctl/config.yaml` nor `~/.config/doctl/config.yaml` . It is placed in `${HOME}/Library/Application Support/doctl/config.yaml`

### CODE REVIEW

**Comment by hilary** [comment]
While few of us are used to thinking of `${HOME}/Library/Application Support` as where application config files go, it is the canonical location for config files on Darwin.

Think of it this way: by default, applications should not have access to each other's configuration files. Apple has always done better when it comes to security and, by default, want apps not to go distributing themselves around your stuff willy-nilly. 😄 

See also: https://golang.org/pkg/os/#UserConfigDir

**Comment by StevenH1901** [comment]
Sorry, I'm slightly confused. I just want to make an update to the documentation so that it's clear if you're installing via brew on OSX, the config files will be placed in `${HOME}/Library/Application Support`. Currently it reads as though it will be placed in `${XDG_CONFIG_HOME}/doctl/config.yaml` which is not correct.

**Comment by hilary** [comment]
No, I'm the one who should apologize! Yup, a documentation update is just what we need. Thanks for catching that.

**Comment by MattIPv4** [comment]
Hey, @StevenH1901 - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

**Pull request merged**
