### PR TITLE
Include Package Managers Install Instructions

### LINKED ISSUE #29: Release to Package Managers
You should release it to several different package managers such as [Homebrew](http://brew.sh) and APT repositories (preferably make your own).

### PR DESCRIPTION
**Pull request by ZacharyDuBois**
Update the `README.md` to include installation through package managers.

Closes #29

### CODE REVIEW

**Comment by bryanl** [comment]
Hello, the content looks fine, but instead of adding an option 3, could you make this option 1, and bump the other ones down?

**Comment by ZacharyDuBois** [comment]
@bryanl No problem, I was going to do that but, I didn't know if there was a reason that brew wasn't listed.

**Comment by bryanl** [comment]
@ZacharyDuBois squash these commits, and its :+1:

**Comment by ZacharyDuBois** [comment]
@bryanl Squashed :)

**Pull request merged**
