### PR TITLE
remove obsolete windows ssh code

### PR DESCRIPTION
**Pull request by hilary**
Works fine on windows without it; runs green on travis and on my x1.

### CODE REVIEW

**Comment by zachgersh** [comment]
@andrewsomething - since you have a windows machine could you verify that this actually works before we merge? I am unsure if we actually have tests around this functionality.

**Comment by zachgersh** [comment]
> Tested it out on my Windows VM, looks good!

as in SSH'ed or run the tests?

**Comment by andrewsomething** [comment]
Only Linux boxes here in the office, but I do have access to a Windows machine at home. I can give it a try if still needed when I'm back home later.

**Comment by hilary** [comment]
I'm going to go ahead and merge on the basis of @bentranter's tests. I'll add an comment to the release notes. If necessary, we can always revert and/or address specific issues as they arise.

**Pull request merged**
