### PR TITLE
Add many Droplet Actions command

### PR DESCRIPTION
**Pull request by zyegfryed**
* disable_backups
* restore
* rebuild
* rename
* change_kernel
* kernels
* enable_ipv6
* enable_private_networking
* snapshot
* upgrade

### CODE REVIEW

**Comment by tlk** [comment]
Nice addition. Input to the PR:
- log.Fatal error messages contain "to resize" in dropletAction functions that do not resize
- dropletAction functions with lots of duplicate code (could be refactored in a separate commit)

**Comment by zyegfryed** [comment]
Hi @tlk 
I've fixed the first bullet point. For the second one, there's already PR#6 that comes with a solution. So, let's wait a see whether it gets merged, otherwise, feel free to open an new PR to bring this change.

**Comment by tlk** [comment]
Hi @zyegfryed That's great! Let's wait and see what happens with these PR's.

**Comment by bryanl** [comment]
doctl has rev'd to v1, and this is no longer applicable.

**Pull request closed without merging**
