### PR TITLE
Rework README.md to match Community's new tutorial

### LINKED ISSUE #167: allow ``ssh-user`` and ``ssh-port`` to be specified in config file
We are using non standard ssh port and non-root user to admin all machines, we need to specify them via command line every time we want to ``doctl compute ssh``.

### PR DESCRIPTION
**Pull request by xmudrii**
We have been working on updating `doctl` tutorial and this is the first step towards it. This PR improves README. We've corrected installation instructions and added several new things, such as more detailed examples for configuration and shell completions.

Also, this PR closes #167.

The releasing part has been moved to the CONTRIBUTING.md.

/cc @hazel-DO @mauricio @viola @lxfontes

### CODE REVIEW

**Comment by xmudrii** [comment]
Ready for review. :shipit: 

/cc @hazel-DO @mauricio @viola @lxfontes

**Comment by hazel-DO** [comment]
@xmudrii Mind giving me push access to this branch for copyediting?

**Comment by xmudrii** [comment]
@hazel-DO No problem, I've sent you a request :)

**Comment by hazel-DO** [comment]
LGTM! :+1:

**Comment by xmudrii** [comment]
@hazel-DO Thank you very much for the review

**Pull request merged**
