### PR TITLE
k8s: add support for ha flag

### PR DESCRIPTION
**Pull request by sunny-b**
This PR adds support for the `ha` flag for the Kubernetes Create and Update commands. It also makes it so the `HA Control Plane` field is outputted in the JSON response.

cc: @adamwg

### CODE REVIEW

**Review by adamwg — DISMISSED** [review]
lgtm

**Review by bentranter — COMMENTED** [review]
Looks good overall @sunny-b, one request – would be able to add or extend an integration test for this? Adding the flag to [this case](https://github.com/digitalocean/doctl/blob/main/integration/kubernetes_clusters_create_test.go#L130) is probably enough. Thanks!

**Comment by sunny-b** [comment]
@bentranter added `ha` to some of the tests and the tests are passing now

**Review by bentranter — APPROVED** [review]
Looks great! Thanks @sunny-b

**Pull request merged**
