### PR TITLE
Implementing Bash completion

### LINKED ISSUE #90: Bash Completion
Feature request: We need bash completion...

doctl <tab> should show compute, account, auth ...

### PR DESCRIPTION
**Pull request by xmudrii**
This PR implements commands for generating shell completion files.
For now, it only supports Bash, but I plan to make it for ZSH and Fish as well.

## Last update: 2017-03-28

To generate completion code you can use:
```
doctl completion bash # or
doctl completion zsh
```
Code will be printed to your screen. To use it, you need to source it. You have two possibilities:
* Source it in your profile using something like `source <(doctl completion bash)` or for `zsh`: `source <(doctl completion zsh)`
* Redirect it to `doctl.sh` file using `doctl completion bash > doctl.sh` and copy it to `/etc/bash_completion.d/`.

cc @viola @lxfontes 

Fixes #90

### CODE REVIEW

**Comment by yufengwng** [comment]
Stumbled upon this today so not sure if it's too late to chime in, but I feel like the default should just write to stdout. This way, the default is more flexible and it plays well with other command line tools. For example, I can look at it with `doctl completion bash | less` or redirect to write it `doctl completion bash > doctl.sh`. Doing this, we don't necessarily need to add another flag for the filename and thus simplifying the implementation. Even the `source` trick becomes easier: `source <(doctl completion bash)`!

I guess a counter-argument is making sure the filename is right for autocompletion to work, but the end-user should be able to figure it out for their respective shells (or add instructions in the help message)? Anyways, will be glad to see support for zsh soon! :)

**Comment by xmudrii** [comment]
@yufengwng thank you very much for your review. I agree with you and I made a needed changes that are in 0eb5d97.
It is much better to print it directly to screen, so user can decide what to do with it.

I will write instructions in Command's help. For now, it's only `...` and `TODO` marker as I'm bit busy right now. Expect it in day or two, hopefully.

As of ZSH part. Well... it's somewhat complicated. I was not able to find complete documentation for converting Bash to ZSH. Standard instructions(:
```
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
```) doesn't work at all. I have to research possible ways to overcome problems.
Let me know what do you think about above changes.

**Comment by yufengwng** [comment]
@xmudrii thanks for considering my suggestion. The changes look good, aside from perhaps updating L29 to say `completion is used to generate completion script for bash/zsh/fish`. Definitely get another pair of eyes on it since I'm still fairly new to Go and cobra.

As for the instructions, [kubectl](https://github.com/kubernetes/kubernetes/blob/9dec47d/pkg/kubectl/cmd/completion.go) might serve as inspiration, particularly the bits in `completion_long`. I took a look at the bash -> zsh trick. As I understand it, we take the bash completion script and convert it to work with zsh's bashcompinit. I tried my hand at it and it seems to work well. [Here's](https://gist.github.com/yufengwng/146d3fb7d62b23698444825da0f03f3c) what the entire thing might look like, but it seems to only work if you source it, i.e. `source /path/to/doctl_zsh_completion.sh`.

If we're going with the bash to zsh trick, I suggest looking at [this](https://github.com/kubernetes/kubernetes/blob/9dec47d/pkg/kubectl/cmd/completion.go#L135-L299) and [this](https://github.com/redhat-developer/opencompose/pull/32), which is what my gist is based off of. Hope that helps, and thanks for working on it!

**Comment by xmudrii** [comment]
@yufengwng thank you very much once again. I have updated LongCompletion text so please take a look and let me know what do you think about it. Let me know if I left something or made some mistake (mostly grammar ones).
```
completion is used to output completion code for bash/zsh/fish shell.

Before using completion features, you have to source completion code
from your .profile or .bashrc/.zshrc file. This is done by adding
following line to one of above files:
	source <(doctl completion SHELL)

Bash users can as well save it to file and copy it to:
	/etc/bash_completion.d/

Correct arguments for SHELL are: "bash", "zsh" and "fish".

Notes:
1) zsh completions requires zsh 5.2 or newer.
	
2) macOS users have to install bash-completion framework to utilize
completion features. This can be done using homebrew:
	brew install bash-completion

Once installed, you must load bash_completion by adding following
line to your .profile or .bashrc/.zshrc:
	source $(brew --prefix)/etc/bash_completion

Usage:
  doctl completion [command]

Available Commands:
  bash        generate bash completion code
  zsh         generate zsh completion code
  fish        generate fish completion code

Flags:
  -h, --help   help for completion

Global Flags:
  -t, --access-token string   API V2 Access Token
  -c, --config string         config file (default is $HOME/.config/doctl/config.yaml)
  -o, --output string         output format [text|json] (default "text")
      --trace                 trace api access
  -v, --verbose               verbose output

Use "doctl completion [command] --help" for more information about a command.
```

I knew for `kubectl` but I mostly wanted answers why all that code and is everything required but it seems to work great.
I implemented ZSH generation so you can test it if you are interested. Code is available in form of [Gist](https://gist.github.com/xmudrii/8918c78ac3858f65893c99722d4abc60).

About Bash -> ZSH trick, I think it's best solution. Maybe not something glorious, but it doesn't requires a lot of work. `doctl` has many commands and I think it would be very hard to hand-write and maintain it manually. For me, it seems to work really great.

_Fish command is there returning error. I recommended merging this PR as it is, of course if everything beside `fish` is correct. I don't know when I will have time to look into it but I will when I find time._

Let me know what do you think about above changes.

**Comment by mauricio** [comment]
@xmudrii do you mind removing `fish` since it's not working?

**Comment by xmudrii** [comment]
Okay, will do it in few minutes :+1:                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Maurício LinharesSent: utorak, 4. april 2017. 20.39To: digitalocean/doctlReply To: digitalocean/doctlCc: Marko Mudrinić; MentionSubject: Re: [digitalocean/doctl] Implementing Bash completion (#206)@xmudrii do you mind removing fish since it's not working?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/digitalocean/doctl","title":"digitalocean/doctl","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/digitalocean/doctl"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mauricio in #206: @xmudrii do you mind removing `fish` since it's not working?"}],"action":{"name":"View Pull Request","url":"https://github.com/digitalocean/doctl/pull/206#issuecomment-291593540"}}}

**Comment by xmudrii** [comment]
@mauricio is it good enough now? :100:

**Comment by mauricio** [comment]
Awesome stuff @xmudrii !

**Pull request merged**
