### PR TITLE
Expose 'tag-name' argument to the RunDropletDelete command.

### PR DESCRIPTION
**Pull request by timoreimann**
The functionality was already implemented in `RunDropletDelete` but never exposed. With this change, we allow deletion of droplets by tag name through the CLI.

Ideally, I'd also like to add a test case. However, from a quick glance at `droplet_test.go` I cannot easily see how to do that -- the existing tests (like `TestDropletDeleteByTag`) seems to attach the tag name argument separately from the `Droplet()` function. It looks like we should be testing things differently to actually run through the system-under-test, though chances are I might be missing something. Pointers welcome. :)

### CODE REVIEW

**Comment by aybabtme** [comment]
lgtm

**Comment by eddiezane** [comment]
Thank you for the PR!

I think we should prevent the user from shooting themselves in the foot by listing the droplets that will be deleted in the confirmation prompt.

Thoughts?

**Comment by timoreimann** [comment]
@eddiezane sounds like a great idea to me. Will get back to you as soon as I manage to extend the PR accordingly.

**Comment by timoreimann** [comment]
Pushed the suggested change. PTAL again.

**Comment by eddiezane** [comment]
@timoreimann thanks for the PR!

Would you please shoot me an email when you get a chance? My GH username [at] digitalocean [dot] com.

**Pull request merged**
