### PR TITLE
vpc: modify vpc update cmd to enable users to only pass arguments that they intend to update

### PR DESCRIPTION
**Pull request by andrewlouis93**

### CODE REVIEW

**Review by andrewsomething — APPROVED** [review]
:+1: Looks good! Will merge on :green_circle:

**Review by andrewsomething — CHANGES_REQUESTED** [review]
Actually, looks like one of the integration tests needs an update:

```
    vpc_update_test.go:87: 
        	Error Trace:	vpc_update_test.go:87
        	            				spec.go:269
        	            				spec.go:262
        	            				parser.go:133
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestRun/doctl/vpcs/update/all_required_flags_are_passed/updates_the_VPC
        	Messages:   	received error output: Error: PATCH http://127.0.0.1:38131/v2/vpcs/vpc-uuid: 405 
```

https://github.com/digitalocean/doctl/blob/master/integration/vpc_update_test.go#L38

**Comment by andrewlouis93** [comment]
Done, thanks @andrewsomething!

**Review by cristianosanchez — APPROVED** [review]
LGTM

**Review by andrewsomething — APPROVED** [review]
:+1:

**Pull request merged**
