### PR TITLE
vendor: fix vektra/{errors,mockery} to static vendoring instead submodule

### LINKED ISSUE #147: go get not working
```
$ go get github.com/digitalocean/doctl/cmd/doctl
# cd /opt/go/src/github.com/digitalocean/doctl; git submodule update --init --recursive
fatal: no submodule mapping found in .gitmodules for path 'vendor/github.com/vektra/errors'
package github.com/digitalocean/doctl/cmd/doctl: exit status 128
```

### PR DESCRIPTION
**Pull request by zchee**
I can't test because `$GOPATH` and related import package path(actually, I don't know how to test it way), But maybe solved the can't `go get` issue.

In the detailed of issue cause, IIRC
```sh
fatal: no submodule mapping found in .gitmodules for path 'vendor/github.com/vektra/errors'
```
is caused by git-submodule vendoring.
See https://github.com/digitalocean/doctl/tree/bb6a9630426adc1fed74f93df6f749deae6530aa/vendor/github.com/vektra
https://github.com/digitalocean/doctl/tree/bb6a9630426adc1fed74f93df6f749deae6530aa/vendor/golang.org/x
So, delete `vendor/github.com/vektra/{errors,mockery}` and `vendor/golang.org/x/tools` directory with
```sh
git rm --cached vendor/github.com/vektra/errors
git rm --cached vendor/github.com/vektra/mockery
git rm --cached vendor/golang.org/x/tools # which depends on github.com/vektra/mockery
```

 and re-fetch using

```sh
gvt fetch github.com/vektra/errors
gvt fetch github.com/vektra/mockery # automatically fetch golang.org/x/tools together
```

Fixes #147,#150

### CODE REVIEW

**Comment by xmudrii** [comment]
Good job! This does looks good to me. However, I'm on mobile and not able to test it now.cc @viola @caueguerra @lxfontes

**Comment by xmudrii** [comment]
This should also fix #42

**Comment by lyda** [comment]
Be really nice if this gets accepted.

**Pull request merged**
