### PR TITLE
Database User Auth Reset support for All DB Engines

### PR DESCRIPTION
**Pull request by rpmoore**
Updating reset user auth for databases to work for multiple database types including mongo

### CODE REVIEW

**Comment by andrewsomething** [comment]
Looks like wee need to update the API docs:

> Note: Resetting user authentication is not supported for PostgreSQL and Redis clusters.

https://docs.digitalocean.com/reference/api/api-reference/#operation/reset_auth

**Comment by rpmoore** [comment]
> Looks like wee need to update the API docs:
> 
> > Note: Resetting user authentication is not supported for PostgreSQL and Redis clusters.
> 
> https://docs.digitalocean.com/reference/api/api-reference/#operation/reset_auth

That is correct. Where is the best place to do that?

**Comment by scotchneat** [comment]
@rpmoore I pushed a PR for the docs changes - https://github.com/digitalocean/openapi/pull/527

**Review by andrewsomething — APPROVED** [review]
:+1:  LGTM!

**Pull request merged**
